### PR TITLE
Add game icon

### LINKED ISSUE #19: Add game icon
- [x] add the icon (#32)
- [ ] use the icon for the executable file
- [ ] use the icon for the game window

### PR DESCRIPTION
**Pull request by rexim**

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I've removed "Close #19" words from the PR description, because that doesn't actually close the issue. We still need to use the icon in the proper places (Windows binary and the game window), but I'll implement that part myself.

Thank you!

**Review by ForNeVeR — APPROVED** [review]

**Comment by rexim** [comment]
@ForNeVeR just wanna point out that this wasn't declared as the part of the scope of #19. In fact the scope of #19 wasn't defined at all.

It's actually my bad. I should've asked for the scope clarification before starting working on this task. Will do next time.

**Comment by ForNeVeR** [comment]
@rexim there's another problem here: I don't believe this is covered by CC-BY license.

Look: in #31 we've had agreement that all of your _present_ (at that moment) contributions could be relicensed. And now you've created a PR from the commit 815984119463c8ab3328f339d2bf0023e1a213fb (_before_ I've added the CC-BY license to the repo).

I hope everything is okay, and we're still licensing this icon under CC-BY?

Re #19: not a problem at all. Vague and undefined issue scopes is a thing project maintainer should be concerned with. So, I'm sorting that out.

**Comment by ForNeVeR** [comment]
I've updated the description of #19 to be more clear about what should be done.

**Comment by rexim** [comment]
I'm licensing all of my artistic contributions to this specific project under the terms of cc-by.

**Comment by ForNeVeR** [comment]
Thanks!

**Pull request merged**
